config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /es|en/ do  
  end
    devise_for :users
    root 'welcomes#home'
    resources :users, :categories, :projects, :articles

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :categories, dependent: :destroy
  validates :email, :presence => {:message => "No debe estar en blanco"}
  validates :name, length: { maximum: 50, too_long: "%{count} caracteres es el máximo permitido" }
  include PermissionsConcern
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_user, except: [:index]

  def index
    @users = User.all
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if current_user.is_admin?
        if @user.update(user_params)
          format.html { redirect_to @user, :notice => 'El usuario fue editado exitosamente' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @user, :alert => 'No tienes permisos para realizar esta acción' }
      end
    end
  end

  def destroy
    respond_to do |format|
      if current_user.is_admin?
        if @user.destroy
          format.html { redirect_to users_url,
            :alert => 'El usuario fue eliminado exitosamente' }
          format.json { head :no_content }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to '/users', :alert => 'No tienes permisos para realizar esta acción' }
      end
    end
  end

  private

  def set_user
    if User.exists?(params[:id])
      @user = User.find(params[:id])
    else
      respond_to do |format|
        format.html { redirect_to users_path, :alert => 'El usuario no existe' }
      end
    end
  end

  def user_params
    params.require(:user).permit(:email, :name, :permission_level, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="container_form">
    <h1><strong>Editar Usuario</strong></h1>
    <% @user.errors %>
    <%= semantic_form_for @user do |f| %>
    <%= f.input :email %>
    <%= f.input :name, label: "Nombre" %>
    <%if current_user.is_admin? %>
      <%= f.input :permission_level, name: "quantity", min: "1", max: "3", label: "Nivel (1 = Usuario; 2 = Asistente; 3 = Admin)" %>
    <%else%>
      <%= f.input :permission_level, name: "quantity", min: "1", max: "2", label: "Nivel (1 = Usuario; 2 = Asistente)" %>
    <%end%>
    <div class="field">
      <%= f.actions do %>
      <%= f.submit "Guardar" %>
      <%= link_to 'Usuarios', users_path %> |
      <%= link_to 'Regresar', :back %>
      <% end %>
    </div>


    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="container_form container_index">
  <h1><strong>Usuarios</strong></h1>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Correo</th>
          <th>Nivel</th>
          <th colspan="3"></th>
        <tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
          <% if user.name.blank? %>
            <td></td>
          <% else %>
            <td><%= link_to user.name, user %></td>
          <% end %>
          <% if user.email.blank? %>
            <td></td>
          <% else %>
            <td><%= user.email %></td>
          <% end %>
          <%case user.permission_level
            when 1 %>
            <td>Usuario</td>
            <% when 2 %>
            <td>Asistente</td>
            <% when 3 %>
            <td>Admin</td>
          <%end%>
            <td><%= link_to  "Detalle", user %></td>
            <td><%= link_to  "Editar", edit_user_path(user) %></td>
            <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: '¿Estás seguro de eliminar este usuario?' } %></td>
          <% end %>
          </tr>
        </tbody>
      </table>
      <div class="field">
        <%= link_to "Regresar", :back %> 
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="container_form">
    <div class="field">
      <h1><strong><%= @user.name %></strong></h1>
    </div>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <th>Correo</th>
          <th>Nivel</th>
          <th></th>
        </thead>
        <tbody>
          <tr>
            <% if @user.email.blank? %>
            <td></td>
            <% else %>
            <td><%= @user.email %></td>
            <% end %>
            <%case @user.permission_level
            when 1 %>
            <td>Usuario</td>
            <% when 2 %>
            <td>Asistente</td>
            <% when 3 %>
            <td>Admin</td>
            <%end%>
            <% if user_signed_in? && current_user.is_admin? %>
            <td><%= link_to  "Editar", edit_user_path(@user) %></td>
            <td><%= link_to 'Eliminar', @user, method: :delete, data: { confirm: '¿Estás seguro de eliminar este usuario?' } %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <hr>
      <div class="field">
        <%= link_to 'Usuarios', users_path %> |
        <%= link_to "Regresar", :back %>
      </div>
    </div>
  </div>
</div>