config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /es|en/ do  
  end
    devise_for :users
    root 'welcomes#home'
    resources :users, :categories, :projects, :articles

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :category, dependent: :destroy
  validates :title, :urlgit, :urlweb, :urlimg, :presence => {:message => "No debe estar en blanco"}
  validates :title, length: { maximum: 50, too_long: "%{count} caracteres es el máximo permitido" }
  validates :urlgit, :urlweb, :urlimg, length: { maximum: 100, too_long: "%{count} caracteres es el máximo permitido" }

  has_attached_file :image, styles: { large: "640X640>", medium: "300x300>", thumb: "100x100>", mini: "40x40>"}, :default_url => "missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_asistant!, only: [:new, :edit, :update]
  before_action :authenticate_admin!, only: [:destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    respond_to do |format|
      if current_user.is_asistant?
        if @project.save
          format.html { redirect_to @project, notice: 'El proyecto fue creado exitosamente' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @project, :alert => 'No tienes permisos para realizar esta acción' }
      end

    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if current_user.is_asistant?
        if @project.update(project_params)
          format.html { redirect_to @project, notice: 'El proyecto fue editado' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to @project, :alert => 'No tienes permisos para realizar esta acción' }
      end

    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    respond_to do |format|
      if current_user.is_admin?
        @project.destroy
          format.html { redirect_to projects_url, notice: 'El proyecto fue eliminado' }
          format.json { head :no_content }
      else
        format.html { redirect_to '/projects', :alert => 'No tienes permisos para realizar esta acción' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_project
      if Project.exists?(params[:id])
        @project = Project.find(params[:id])
      else
        respond_to do |format|
          format.html { redirect_to users_path, :alert => 'El proyecto no existe' }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :user_id, :image, :urlgit, :urlweb, :urlimg, :category_ids => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> Proyecto</h1>
<% @project.errors %>
<%= semantic_form_for @project do |f| %>
<%= f.inputs do %>
<%= f.input :title, :label => I18n.t('title') %>
<%= f.input :description, :label => I18n.t('description') %>
<%= f.input :urlgit, label: "GitHub" %>
<%= f.input :urlweb, label: "Url Web" %>
<%= f.input :urlimg, label: "Url Imagen" %>
<%= f.file_field :image %>
<%= f.input :category, :as => :check_boxes, label: "Categorías" %>
<% end %>
<% if user_signed_in? && current_user.is_asistant? || user_signed_in? && current_user.is_admin? %>
<div class="field">
  <%= f.actions do %>
  <%= f.action :submit, :as => :input, label: "Guardar" %>
  <% end %>
</div>
<% end %>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="container_form">
    <%= render "form", name: "Editar" %>
    <div class="field">
      <%= link_to 'Detalle', @project %> |
      <%= link_to 'Proyectos', projects_path %> |
      <%= link_to 'Regresar', :back %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="container_form container_index">
    <h1><strong>Proyectos</strong></h1>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th colspan="1"></th>
            <th>Titulo</th>
            <th>Descripción</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
          <tr>
          <td><%= link_to (image_tag project.image.url(:thumb)), project %></td>
          <% if project.title.blank? %>
            <td></td>
          <% else %>
            <td><%= project.title %></td>
          <% end %>
          <% if project.description.blank? %>
            <td></td>
          <% else %>
            <td><%= truncate(project.description, length: 30) %></td>
          <% end %>
            <td><%= link_to 'Detalle', project %></td>
            <% if user_signed_in? && current_user.is_asistant? %>
            <td><%= link_to 'Editar', edit_project_path(project) %></td>
            <% end %>
            <% if user_signed_in? && current_user.is_admin? %>
            <td><%= link_to 'Eliminar', project, method: :delete, data: { confirm: '¿Estás seguro de eliminarlo?' } %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    </div>
    <div class="field">
      <% if user_signed_in? && current_user.is_asistant? || user_signed_in? && current_user.is_admin? %>
      <%= link_to 'Nuevo Proyecto', new_project_path %> |
      <%= link_to "Regresar", :back %>
      <% else %>
      <%= link_to "Regresar", :back %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="container_form">
    <%= render "form" %>
    <div class="field">
      <%= link_to 'Proyectos', projects_path %> |
      <%= link_to 'Regresar', :back %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="container_form">
    <div class="field">
      <h1>Proyecto: <span><%= @project.title %></span></h1>
    </div>
    <div class="field">
      <%= image_tag @project.image.url(:medium) %>
    </div>
    <div class="row">
      <div class="field col-md-8">
        <h4><strong>Descripción:</strong></h4>
        <p><%= @project.description %></p>
      </div>
      <div class="field col-md-4">
        <h4><strong>Categorías:</strong></h4>
        <% @project.category.each do |category| %>
        <%= link_to category.title, category %>, 
        <% end %>
      </div>
    </div>
    <hr>
    <div class="field">
      <% if user_signed_in? && current_user.is_asistant? || user_signed_in? && current_user.is_admin? %>
      <%= link_to 'Editar', edit_project_path(@project) %> |
      <%= link_to 'Proyectos', projects_path %> |
      <%= link_to 'Regresar', :back %>
      <% else %>
      <%= link_to 'Proyectos', projects_path %> |
      <%= link_to 'Regresar', :back %>
      <% end %>
    </div>
  </div>
</div>